# Netlify configuration for static site deployment
[build]
  # No build command needed for static HTML site
  command = ""
  # Publish directory is the root directory
  publish = "."

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle SPA routing (if needed in future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
